config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  resources :tweets
  get "quizzes/start", to: "quizzes#start"
  get "quizzes/result", to: "quizzes#result"
  get "quizzes/:index", to: "quizzes#show", as: :quiz
  post "quizzes/answer", to: "quizzes#answer"
  root 'hello#index' 
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quiz.rb
class Quiz < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end

  def link
    
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def start
    country = params[:country]
    quizzes = Quiz.where(country: country).shuffle

    session[:quiz_ids] = quizzes.first(5).map(&:id)
    session[:current_index] = 0
    session[:score] = 0

    redirect_to quiz_path(index: 0)
  end

  def show
    quiz_ids = session[:quiz_ids] || []
    index = params[:index].to_i

    if index >= quiz_ids.length
      redirect_to quizzes_result_path and return
    end

    @quiz = Quiz.find(quiz_ids[index])
    @index = index
  end

  def answer
    selected_option = params[:selected_option].to_i
    index = params[:index].to_i
    quiz = Quiz.find(session[:quiz_ids][index])

    if selected_option == quiz.correct_option
      session[:score] += 1
      current_user.increment!(:points, 1)  # ← ここを追加！！
    end
  
    session[:current_index] = index + 1

    if session[:current_index] >= session[:quiz_ids].length
      redirect_to quizzes_result_path
    else
      redirect_to quiz_path(index: session[:current_index])
    end
  end

  def result
    @score = session[:score]
    @total = session[:quiz_ids]&.length || 0

    # セッションをクリア
    session[:quiz_ids] = nil
    session[:current_index] = nil
    session[:score] = nil
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tweets = Tweet.all
    search = params[:search]
    @tweets = @tweets.joins(:user).where("body LIKE ?", "%#{search}%") if search.present?
    @tweets = @tweets.page(params[:page]).per(3)
  end
  
  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)

    tweet.user_id = current_user.id
    
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/hello/index.html.erb
<%= link_to "ログイン", tweets_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/hello/link.html.erb
My name is GeekSalon.
<%= link_to 'トップページ', hello_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geektwitter3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quizzes/result.html.erb
<h1>クイズ結果</h1>
<p>正解数: <%= @score %> / <%= @total %></p>

<% if user_signed_in? %>
  <p>あなたの累計ポイント: <%= current_user.points %> pt</p>
<% end %>


<%= link_to "トップへ戻る", tweets_path %>

app/views/quizzes/show.html.erb
<h1>第 <%= @index + 1 %> 問</h1>
<p><%= @quiz.question %></p>

<%= form_with url: quizzes_answer_path, method: :post do %>
  <%= hidden_field_tag :index, @index %>

  <label><%= radio_button_tag :selected_option, 1 %> <%= @quiz.option1 %></label><br>
  <label><%= radio_button_tag :selected_option, 2 %> <%= @quiz.option2 %></label><br>
  <label><%= radio_button_tag :selected_option, 3 %> <%= @quiz.option3 %></label><br>

  <%= submit_tag "回答して次へ" %>
<% end %>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body, :size => 140 %> 
  <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<h1>GeekTwitter</h1>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<h3>Tweet一覧</h3>

<h1>国を選んでクイズスタート！</h1>

<%= link_to "中国クイズを始める", quizzes_start_path(country: "china") %><br><br>
<%= link_to "日本クイズを始める", quizzes_start_path(country: "japan") %>

<h3>投稿を検索</h3>
 <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

<%= page_entries_info @tweets %>
<%= paginate @tweets %>

<%= link_to "新規投稿へ", new_tweet_path %>
<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
      <%= t.user.email %>
      <%= t.body %>
      <%= t.created_at %>
      <% if t.image.attached? %>
          <%= image_tag t.image, size: '250x200'%>
      <% end %>
      <%= link_to "詳細へ", tweet_path(t.id) %>
      <%= link_to "編集する", edit_tweet_path(t.id) %>
      <%= button_to "削除する", tweet_path(t.id), method: :delete %> 
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<h1>GeekTwitter</h1>
<h3>新規Tweet</h3>
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <%= f.submit "Tweetする" %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
  <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
</div>

<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>